# Generated by Django 2.0.3 on 2018-06-11 05:20

from django.db import migrations, models
import profile_pic.models
import profile_pic.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_DJ_name', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to=profile_pic.models.user_path, validators=[profile_pic.validations.FileValidator])),
            ],
        ),
    ]
