# Generated by Django 2.0.3 on 2018-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_model',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
    ]
